--Drop DATABASE QuanLyDiemSinhVienN8
CREATE DATABASE QuanLyDiemSinhVienN8
GO
USE QuanLyDiemSinhVienN8
GO

CREATE TABLE [TAIKHOAN](
  TaiKhoan varchar(20),
  MatKhau varchar(20)
);
GO
CREATE TABLE [KHOA] (
	MaKhoa varchar(20) NOT NULL,
	TenKhoa varchar(255) NOT NULL,
  CONSTRAINT [PK_KHOA] PRIMARY KEY CLUSTERED
  (
  [MaKhoa] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PHONG] (
	MaPhong varchar(20) NOT NULL,
	SoCho integer NOT NULL,
  CONSTRAINT [PK_PHONG] PRIMARY KEY CLUSTERED
  (
  [MaPhong] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [MONHOC] (
	MaMH varchar(20) NOT NULL,
	TenMH varchar(255) NOT NULL,
	TinChi integer NOT NULL,
  CONSTRAINT [PK_MONHOC] PRIMARY KEY CLUSTERED
  (
  [MaMH] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [HOCPHAN] (
	MaHP varchar(20) NOT NULL,
	MaMH varchar(20) NOT NULL,
	HocKy varchar(20) NOT NULL,
	Nam integer NOT NULL,
	MaCB varchar(20) NOT NULL,
  CONSTRAINT [PK_HOCPHAN] PRIMARY KEY CLUSTERED
  (
  [MaHP] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [DIEM] (
  MaMH varchar(20) not null,
	MASV varchar(20) NOT NULL,
	MaHP varchar(20) NOT NULL,
	Diem decimal NOT NULL,
  CONSTRAINT [PK_DIEM] PRIMARY KEY CLUSTERED
  (
  [MASV] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SINHVIEN] (
	MaSV varchar(20) NOT NULL,
	TenSV varchar(255) NOT NULL,
	MaKhoa varchar(20) NOT NULL,
  CONSTRAINT [PK_SINHVIEN] PRIMARY KEY CLUSTERED
  (
  [MaSV] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [CANBO] (
	MaCB varchar(20) NOT NULL,
	TenCB varchar(255) NOT NULL,
	MaKhoa varchar(20) NOT NULL,
  CONSTRAINT [PK_CANBO] PRIMARY KEY CLUSTERED
  (
  [MaCB] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [LICHTHI] (
	Phong varchar(20) NOT NULL,
  ThoiGian date,
	CanBo varchar(20) NOT NULL,
	MaHP varchar(20) NOT NULL,
  CONSTRAINT [PK_LICHTHI] PRIMARY KEY CLUSTERED
  (
  [Phong] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO



ALTER TABLE [HOCPHAN] WITH CHECK ADD CONSTRAINT [HOCPHAN_fk0] FOREIGN KEY ([MaMH]) REFERENCES [MONHOC]([MaMH])
ON UPDATE NO ACTION
GO
ALTER TABLE [HOCPHAN] CHECK CONSTRAINT [HOCPHAN_fk0]
GO
ALTER TABLE [HOCPHAN] WITH CHECK ADD CONSTRAINT [HOCPHAN_fk1] FOREIGN KEY ([MaCB]) REFERENCES [CANBO]([MaCB])
ON UPDATE NO ACTION
GO
ALTER TABLE [HOCPHAN] CHECK CONSTRAINT [HOCPHAN_fk1]
GO

ALTER TABLE [DIEM] WITH CHECK ADD CONSTRAINT [DIEM_fk0] FOREIGN KEY ([MASV]) REFERENCES [SINHVIEN]([MaSV])
ON UPDATE NO ACTION
GO
ALTER TABLE [DIEM] CHECK CONSTRAINT [DIEM_fk0]
GO
ALTER TABLE [DIEM] WITH CHECK ADD CONSTRAINT [DIEM_fk1] FOREIGN KEY ([MaHP]) REFERENCES [HOCPHAN]([MaHP])
ON UPDATE NO ACTION
GO
ALTER TABLE [DIEM] CHECK CONSTRAINT [DIEM_fk1]
GO

ALTER TABLE [SINHVIEN] WITH CHECK ADD CONSTRAINT [SINHVIEN_fk0] FOREIGN KEY ([MaKhoa]) REFERENCES [KHOA]([MaKhoa])
ON UPDATE NO ACTION
GO
ALTER TABLE [SINHVIEN] CHECK CONSTRAINT [SINHVIEN_fk0]
GO

ALTER TABLE [CANBO] WITH CHECK ADD CONSTRAINT [CANBO_fk0] FOREIGN KEY ([MaKhoa]) REFERENCES [KHOA]([MaKhoa])
ON UPDATE NO ACTION
GO
ALTER TABLE [CANBO] CHECK CONSTRAINT [CANBO_fk0]
GO

ALTER TABLE [LICHTHI] WITH CHECK ADD CONSTRAINT [LICHTHI_fk0] FOREIGN KEY ([Phong]) REFERENCES [PHONG]([MaPhong])
ON UPDATE NO ACTION
GO
ALTER TABLE [LICHTHI] CHECK CONSTRAINT [LICHTHI_fk0]
GO
ALTER TABLE [LICHTHI] WITH CHECK ADD CONSTRAINT [LICHTHI_fk1] FOREIGN KEY ([CanBo]) REFERENCES [CANBO]([MaCB])
ON UPDATE NO ACTION
GO
ALTER TABLE [LICHTHI] CHECK CONSTRAINT [LICHTHI_fk1]
GO
ALTER TABLE [LICHTHI] WITH CHECK ADD CONSTRAINT [LICHTHI_fk2] FOREIGN KEY ([MaHP]) REFERENCES [HOCPHAN]([MaHP])
ON UPDATE NO ACTION
GO
ALTER TABLE [LICHTHI] CHECK CONSTRAINT [LICHTHI_fk2]
GO

--DangNhap
CREATE PROC proc_DangNhap @tk VARCHAR(20) , @mk VARCHAR(20)
AS
BEGIN
	SELECT * FROM TaiKhoan WHERE TaiKhoan = @tk AND MatKhau = @mk
END
GO
--exec proc_DangNhap taikhoan, matkhau

INSERT INTO [TAIKHOAN] VALUES('taikhoan','matkhau')

INSERT INTO [KHOA](MaKhoa, TenKhoa)
VALUES('CNTT','Cong Nghe Thong Tin')


INSERT INTO [SINHVIEN](MaSV, TenSV, MaKhoa)
VALUES('47.01.104.109','Tran Nguyen Khang', 'CNTT')
INSERT INTO [SINHVIEN](MaSV, TenSV, MaKhoa)
VALUES('47.01.104.001','Dang Van Lam', 'CNTT')
UPDATE SINHVIEN SET TenSV='a', MaKhoa='CNTT' WHERE MaSV='47.01.104.001'
